apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
  annotations:
spec:
  selector: 
    app: grafana
  clusterIP: None
  ports:
    - name: "grafana"
      port: 3000
      targetPort: 3000
